baseurl = "http://lipeggy.com/"
languageCode = "en-us"

title = "Peggy Li"

[params]
	twitter = "_peggyli"
	github = "peggyl"
	linkedin = "peggyli224"
	ga_api_key = "UA-60717155-1"
	author = "Peggy Li"
