baseurl = "http://lipeggy.com/"
languageCode = "en-us"

theme = "haydn"

title = "Peggy Li"

[permalinks]
    post = "/:year/:month/:day/:title"

[params]
	twitter = "_peggyli"
	github = "peggyl"
	linkedin = "peggyli224"
	ga_api_key = "UA-60717155-1"
	author = "Peggy Li"
    contact = "mailto:hi@lipeggy.com"
